config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/Parallel-in-Time/pySDC:
      branch: master
      repo: https://github.com/Parallel-in-Time/pySDC
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Parallel-in-Time/pySDC git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-viridian-nightingale.sh
        container: qc.acc_blurry-rose-nightingale
  QC.Doc:
    repos:
      github.com/Parallel-in-Time/pySDC find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-aqua-sponge.sh
        container: qc.doc_crabby-turquoise-labradoodle
      github.com/Parallel-in-Time/pySDC git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-black-crane.sh
        container: qc.doc_cozy-tangerine-peccary
      github.com/Parallel-in-Time/pySDC markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-fuchsia-spitz.sh
        container: qc.doc_shabby-magnolia-wrasse
      github.com/Parallel-in-Time/pySDC restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-cyan-wombat.sh
        container: qc.doc_smelly-cyan-heron
  QC.Lic:
    repos:
      github.com/Parallel-in-Time/pySDC licensee:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-teal-bat.sh
        container: qc.lic_homey-lemon-hare
  QC.Met:
    repos:
      github.com/Parallel-in-Time/pySDC cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-xanthic-spider.sh
        container: qc.met_bumpy-goldenrod-deer
  QC.Sec:
    repos:
      github.com/Parallel-in-Time/pySDC bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-cream-cow.sh
        container: qc.sec_flabby-corn-termite
  QC.Sty:
    repos:
      github.com/Parallel-in-Time/pySDC flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-magnolia-bloodhound.sh
        container: qc.sty_wimpy-wisteria-crab
      github.com/Parallel-in-Time/pySDC jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-teal-bloodhound.sh
        container: qc.sty_shaggy-vermilion-yak
  QC.Ver:
    repos:
      github.com/Parallel-in-Time/pySDC get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-purple-sheep.sh
        container: qc.ver_chewy-aqua-ferret
timeout: 5400
