config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/Parallel-in-Time/pySDC:
      branch: master
      repo: https://github.com/Parallel-in-Time/pySDC
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Parallel-in-Time/pySDC git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-cerise-avocet.sh
        container: qc.acc_bluesy-teal-bison
  QC.Doc:
    repos:
      github.com/Parallel-in-Time/pySDC find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-peach-mastiff.sh
        container: qc.doc_silly-olivine-ant
      github.com/Parallel-in-Time/pySDC git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-indigo-crab.sh
        container: qc.doc_squirrely-plum-bear
      github.com/Parallel-in-Time/pySDC markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-red-snail.sh
        container: qc.doc_jumpy-harlequin-earwig
      github.com/Parallel-in-Time/pySDC restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-burgundy-elephant.sh
        container: qc.doc_hilly-firebrick-quetzal
  QC.Lic:
    repos:
      github.com/Parallel-in-Time/pySDC licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-bronze-capuchin.sh
        container: qc.lic_tacky-pumpkin-scorpion
  QC.Met:
    repos:
      github.com/Parallel-in-Time/pySDC cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-fuchsia-tarantula.sh
        container: qc.met_lovely-teal-impala
  QC.Sec:
    repos:
      github.com/Parallel-in-Time/pySDC bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-puce-zebra.sh
        container: qc.sec_geeky-dandelion-oriole
  QC.Sty:
    repos:
      github.com/Parallel-in-Time/pySDC flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-bronze-bat.sh
        container: qc.sty_snoopy-emerald-cattle
      github.com/Parallel-in-Time/pySDC jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-magnolia-fly.sh
        container: qc.sty_whiny-linen-dragon
  QC.Ver:
    repos:
      github.com/Parallel-in-Time/pySDC get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-thistle-insect.sh
        container: qc.ver_shaggy-persimmon-buffalo
timeout: 5400
